import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Hero from "./components/hero";
import Web3 from "./components/web3";
import Engineering from "./components/engineering";
import Trainings from "./trainings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bear Metal Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body className={inter.className}>
        <Navbar />
        <Hero />
        <Web3 />
        <Engineering />
        <Trainings />
        {children}
      </body>
    </html>
  );
}
